services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookshop_network

 backend:
  image: 913524900585.dkr.ecr.eu-central-1.amazonaws.com/book_shop:${IMAGE_VERSION}
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bookshop_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - backend
    networks:
      - bookshop_network

volumes:
  postgres_data:
  static_volume:

networks:
  bookshop_network:
    driver: bridge
