name: Dev Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Artifact
        run: |
          mkdir -p artifacts
          # Package the app. Exclude git, github, and the artifacts folder to prevent recursive archiving.
          tar --exclude='./artifacts' --exclude='./.git' --exclude='./.github' -czvf artifacts/app-${{ github.sha }}.tar.gz .

      - name: Commit Artifact to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add build artifact app-${{ github.sha }}.tar.gz"
          branch: dev
          file_pattern: 'artifacts/*.tar.gz'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/book_shop_docker-main/book_shop_docker-main-main
            
            git fetch origin dev
            git reset --hard origin/dev
            
            export ARTIFACT_NAME=app-${{ github.sha }}.tar.gz
            
            docker compose -p dev -f docker-compose.yml up --build -d
