name: Prod Deployment

on:
  push:
    branches:
      - prod

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/book_shop_docker-main/book_shop_docker-main-main

            git fetch origin prod
            git reset --hard origin/prod

            export IMAGE_VERSION=${{ vars.IMAGE_VERSION }}

            sed -i "s|image: .*|image: 913524900585.dkr.ecr.eu-central-1.amazonaws.com/book_shop:$IMAGE_VERSION|g" docker-compose.yml

            docker compose -p prod pull

            docker compose -p prod down

            docker compose -p prod up -d
